"use client";

import { useState } from "react";
import { format, parseISO, subDays } from "date-fns";
import { FileDown, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useConsoleStore } from "@/lib/store";
import { currentOperator } from "@/lib/mock-data";
import { cn } from "@/lib/utils";
import type { AttestationReport } from "@/types";

const FRAMEWORKS = ["HIPAA", "SOC 2", "ISO 27001", "PCI-DSS", "GDPR", "NIST", "FERPA", "FedRAMP"];

const SECTION_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "exec_summary", label: "Executive Summary" },
  { id: "per_tenant", label: "Per-Tenant Posture" },
  { id: "violations", label: "Violation History" },
  { id: "remediations", label: "Remediation Audit Trail" },
  { id: "evidence", label: "Evidence Packages (signed)" },
  { id: "operators", label: "Operator Access Logs" },
];

interface AttestationExportProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function AttestationExportDialog({
  open,
  onOpenChange,
}: AttestationExportProps) {
  const tenants = useConsoleStore((s) => s.tenants);
  const matrixCells = useConsoleStore((s) => s.matrixCells);
  const compliancePosture = useConsoleStore((s) => s.compliancePosture);
  const recordReport = useConsoleStore((s) => s.recordAttestationReport);

  const [title, setTitle] = useState("Rubrik MSP Operations — Isolation Compliance Attestation");
  const [periodEnd] = useState(() => format(new Date(), "yyyy-MM-dd"));
  const [periodStart] = useState(() => format(subDays(new Date(), 30), "yyyy-MM-dd"));
  const [frameworks, setFrameworks] = useState<string[]>(["HIPAA", "SOC 2", "ISO 27001"]);
  const [tenantScope, setTenantScope] = useState<string>("all");
  const [sections, setSections] = useState<string[]>(SECTION_OPTIONS.map((s) => s.id));
  const [distribution, setDistribution] = useState("compliance@rubrik-msp.com, security@rubrik-msp.com");
  const [generating, setGenerating] = useState(false);
  const [progressLabel, setProgressLabel] = useState("");

  const reset = () => {
    setGenerating(false);
    setProgressLabel("");
  };

  const onGenerate = async () => {
    setGenerating(true);
    const messages = [
      "Aggregating posture data across 62 tenants…",
      "Compiling violation and remediation history…",
      "Generating signed evidence packages…",
      "Rendering report…",
      "Applying digital signature…",
    ];
    for (const msg of messages) {
      setProgressLabel(msg);
      await new Promise((r) => setTimeout(r, 480));
    }
    const reportId = `ATT-${format(new Date(), "yyyy-MM-dd")}-001`;
    try {
      const { jsPDF } = await import("jspdf");
      const autoTableModule = await import("jspdf-autotable");
      const autoTable = autoTableModule.default ?? autoTableModule;
      const doc = new jsPDF();
      buildPdf(doc, autoTable, {
        title,
        reportId,
        periodStart,
        periodEnd,
        frameworks,
        tenants,
        matrixCells,
        compliancePosture,
        distribution: distribution.split(",").map((s) => s.trim()).filter(Boolean),
        sections,
      });
      doc.save(`${reportId}.pdf`);
    } catch {
      // Fallback: trigger download of a static blob with the metadata
      const blob = new Blob(
        [
          `Rubrik MSP Operations — Attestation Report\n${reportId}\n${title}\nPeriod: ${periodStart} → ${periodEnd}\nFrameworks: ${frameworks.join(", ")}\nGenerated by ${currentOperator.name}.\n`,
        ],
        { type: "text/plain" },
      );
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${reportId}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }

    const report: AttestationReport = {
      id: reportId,
      title,
      generatedAt: new Date().toISOString(),
      generatedBy: currentOperator.name,
      reportingPeriodStart: parseISO(periodStart).toISOString(),
      reportingPeriodEnd: parseISO(periodEnd).toISOString(),
      frameworks,
      tenantCount: tenantScope === "all" ? tenants.filter((t) => t.status === "Active").length : 0,
      distributionList: distribution.split(",").map((s) => s.trim()).filter(Boolean),
    };
    recordReport(report);
    toast.success(`Attestation generated · ${reportId}`, {
      description: `Distributed to ${distribution}.`,
    });
    reset();
    onOpenChange(false);
  };

  const toggleFramework = (f: string) => {
    setFrameworks((cur) => (cur.includes(f) ? cur.filter((x) => x !== f) : [...cur, f]));
  };
  const toggleSection = (id: string) => {
    setSections((cur) => (cur.includes(id) ? cur.filter((x) => x !== id) : [...cur, id]));
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o && !generating) onOpenChange(false);
      }}
    >
      <DialogContent className="max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Generate Attestation Report</DialogTitle>
          <DialogDescription className="text-[12.5px] text-text-secondary">
            Compiles posture, violations, remediations, and evidence into a
            signed PDF for compliance distribution.
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-3 py-2">
          <div>
            <Label className="text-[12px] font-medium text-text-primary">Report Title</Label>
            <Input value={title} onChange={(e) => setTitle(e.target.value)} className="mt-1" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label className="text-[12px] font-medium text-text-primary">Reporting Period</Label>
              <div className="mt-1 rounded-md border border-border-subtle bg-canvas px-3 py-2 text-[12px] text-text-secondary tabular-nums">
                {periodStart} → {periodEnd}
              </div>
            </div>
            <div>
              <Label className="text-[12px] font-medium text-text-primary">Tenant Scope</Label>
              <Select value={tenantScope} onValueChange={setTenantScope}>
                <SelectTrigger className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Active Tenants</SelectItem>
                  <SelectItem value="failures">Tenants with Findings</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div>
            <Label className="text-[12px] font-medium text-text-primary">Frameworks</Label>
            <div className="mt-1 flex flex-wrap gap-1.5">
              {FRAMEWORKS.map((f) => (
                <button
                  key={f}
                  type="button"
                  onClick={() => toggleFramework(f)}
                  className={cn(
                    "h-7 rounded-full px-3 text-[11.5px] font-medium transition-colors",
                    frameworks.includes(f)
                      ? "bg-brand-primary-subtle text-brand-primary-hover"
                      : "bg-secondary text-text-secondary hover:bg-secondary/80",
                  )}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
          <div>
            <Label className="text-[12px] font-medium text-text-primary">Include Sections</Label>
            <ul className="mt-1 grid grid-cols-1 gap-1 sm:grid-cols-2">
              {SECTION_OPTIONS.map((s) => (
                <li key={s.id}>
                  <label className="flex items-center gap-2 rounded-md border border-border-subtle bg-canvas px-2 py-1.5 text-[12px] text-text-primary">
                    <Checkbox
                      checked={sections.includes(s.id)}
                      onCheckedChange={() => toggleSection(s.id)}
                    />
                    {s.label}
                  </label>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <Label className="text-[12px] font-medium text-text-primary">Signed By</Label>
            <div className="mt-1 rounded-md border border-border-subtle bg-canvas px-3 py-2 text-[12.5px] text-text-primary">
              {currentOperator.name}, MSP Administrator
            </div>
          </div>
          <div>
            <Label className="text-[12px] font-medium text-text-primary">Distribution List</Label>
            <Input
              value={distribution}
              onChange={(e) => setDistribution(e.target.value)}
              className="mt-1"
            />
          </div>

          {generating ? (
            <div className="rounded-md border border-brand-primary/30 bg-brand-primary-subtle px-3 py-2 text-[12px] text-text-primary">
              <span className="inline-flex items-center gap-2">
                <Loader2 className="h-3.5 w-3.5 animate-spin text-brand-primary" />
                {progressLabel}
              </span>
            </div>
          ) : null}
        </div>

        <DialogFooter>
          <Button variant="ghost" disabled={generating} onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            disabled={generating || frameworks.length === 0}
            onClick={onGenerate}
            className="gap-2 bg-brand-primary text-white hover:bg-brand-primary-hover"
          >
            <FileDown className="h-4 w-4" />
            {generating ? "Generating…" : "Generate Report"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

interface PdfBuildArgs {
  title: string;
  reportId: string;
  periodStart: string;
  periodEnd: string;
  frameworks: string[];
  tenants: ReturnType<typeof useConsoleStore.getState>["tenants"];
  matrixCells: ReturnType<typeof useConsoleStore.getState>["matrixCells"];
  compliancePosture: ReturnType<typeof useConsoleStore.getState>["compliancePosture"];
  distribution: string[];
  sections: string[];
}

type AutoTableFn = (doc: unknown, options: Record<string, unknown>) => void;

function buildPdf(doc: import("jspdf").jsPDF, autoTable: AutoTableFn, args: PdfBuildArgs) {
  const { title, reportId, periodStart, periodEnd, frameworks, tenants, matrixCells, compliancePosture, distribution, sections } = args;

  const fmt = (s: string) => format(parseISO(s), "MMM d, yyyy");
  const generatedAt = format(new Date(), "MMM d, yyyy HH:mm 'UTC'");

  // Title page
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Isolation Compliance", 14, 32);
  doc.text("Attestation Report", 14, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(title, 14, 52);
  doc.setTextColor(0);

  doc.setFontSize(10);
  doc.text(`Report ID: ${reportId}`, 14, 70);
  doc.text(`Period: ${fmt(parseISO(periodStart).toISOString())} → ${fmt(parseISO(periodEnd).toISOString())}`, 14, 78);
  doc.text(`Generated: ${generatedAt}`, 14, 86);
  doc.text(`Generated by: ${currentOperator.name}, MSP Administrator`, 14, 94);
  doc.text(`Frameworks: ${frameworks.join(", ")}`, 14, 102);
  doc.text(`Distribution: ${distribution.join(", ")}`, 14, 110);

  if (sections.includes("exec_summary")) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Executive Summary", 14, 134);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const failures = matrixCells.filter((c) => c.status === "fail").length;
    const warns = matrixCells.filter((c) => c.status === "warn").length;
    const summary = [
      `Tenants under management: ${tenants.length}`,
      `Active isolation violations: ${failures}`,
      `Active warnings: ${warns}`,
      `Compliance frameworks evaluated: ${frameworks.length}`,
      `Continuous assessment cadence: rolling 4-24h per control`,
    ];
    summary.forEach((line, i) => {
      doc.text(`• ${line}`, 16, 144 + i * 6);
    });
  }

  // TOC
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Table of Contents", 14, 200);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  let tocY = 210;
  ["Per-Tenant Posture", "Violation History", "Remediation Audit Trail", "Compliance Framework Attestation", "Signature Block"].forEach((line, i) => {
    doc.text(`${i + 1}. ${line}`, 16, tocY);
    tocY += 6;
  });

  if (sections.includes("per_tenant")) {
    doc.addPage();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("1. Per-Tenant Posture", 14, 24);
    doc.setFont("helvetica", "normal");
    const rows = tenants.slice(0, 25).map((t) => {
      const myCells = matrixCells.filter((c) => c.tenantId === t.id);
      const fails = myCells.filter((c) => c.status === "fail").length;
      const warns = myCells.filter((c) => c.status === "warn").length;
      const score = Math.max(0, 100 - fails * 15 - warns * 6);
      return [t.name, t.tier, t.status, fails.toString(), warns.toString(), score.toString()];
    });
    autoTable(doc, {
      startY: 32,
      head: [["Tenant", "Tier", "Status", "Failures", "Warnings", "Score"]],
      body: rows,
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [0, 182, 122] },
      theme: "grid",
    });
  }

  if (sections.includes("violations")) {
    doc.addPage();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("2. Violation History", 14, 24);
    doc.setFont("helvetica", "normal");
    const failingCells = matrixCells.filter((c) => c.status === "fail").slice(0, 30);
    const rows = failingCells.map((c) => {
      const t = tenants.find((tt) => tt.id === c.tenantId);
      return [
        t?.name ?? c.tenantId,
        c.controlId,
        format(parseISO(c.violation?.firstDetectedAt ?? c.lastEvaluatedAt), "MMM d, yyyy HH:mm"),
        c.violation?.severity ?? "—",
        c.acknowledged ? "Yes" : "No",
      ];
    });
    autoTable(doc, {
      startY: 32,
      head: [["Tenant", "Control", "First Detected", "Severity", "Acknowledged"]],
      body: rows,
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [220, 38, 38] },
      theme: "grid",
    });
  }

  if (sections.includes("remediations")) {
    doc.addPage();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("3. Remediation Audit Trail", 14, 24);
    doc.setFont("helvetica", "normal");
    autoTable(doc, {
      startY: 32,
      head: [["Operator", "Action", "Tenant", "Control", "Time"]],
      body: [
        [currentOperator.name, "isolation.remediate", "Crawford & Associates LLP", "storage", generatedAt],
        [currentOperator.name, "isolation.banner.acknowledge", "global", "all", generatedAt],
      ],
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [37, 99, 235] },
      theme: "grid",
    });
  }

  doc.addPage();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("4. Compliance Framework Attestation", 14, 24);
  doc.setFont("helvetica", "normal");
  autoTable(doc, {
    startY: 32,
    head: [["Framework", "Compliance %", "Compliant Tenants", "Total"]],
    body: compliancePosture
      .filter((p) => frameworks.includes(p.framework))
      .map((p) => [p.framework, `${p.compliancePct}%`, p.compliantCount.toString(), p.totalCount.toString()]),
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: [0, 182, 122] },
    theme: "grid",
  });

  // Signature page
  doc.addPage();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("5. Signature Block", 14, 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("This report is digitally signed and represents an auditor-grade", 14, 40);
  doc.text("snapshot of isolation posture across all active tenants.", 14, 47);
  doc.setLineWidth(0.4);
  doc.line(14, 80, 110, 80);
  doc.text(`${currentOperator.name}, MSP Administrator`, 14, 88);
  doc.text(`Digitally signed ${generatedAt}`, 14, 96);
  doc.text(`Signature ID: sig-${reportId}`, 14, 104);

  // Footers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(
      `Report ID: ${reportId} · Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.getHeight() - 10,
    );
    doc.setTextColor(0);
  }
}
